// This file was generated by the Zuplo CLI migrate-dev-portal command.
// It is used to configure the Zuplo dev portal.
// You can edit this file to customize the dev portal.
// For more information, see https://zuplo.com/docs/dev-portal/zudoku/configuration/overview
import type { ZudokuConfig } from "zudoku";

const config: ZudokuConfig = {
  redirects: [{ from: "/", to: "/api" }],
  site: {
    title: "Mockbin",
    logo: {
      src: {
        light: "mockbin-black.svg",
        dark: "mockbin-white.svg",
      },
      alt: "Mockbin",
      href: "/",
    },
  },
  navigation: [
    {
      type: "link",
      to: "/api",
      label: "API Reference",
    },
  ],
  apis: [
    {
      type: "file",
      input: "../config/routes.oas.json",
      path: "/api",
    },
  ],
};
export default config;
